### PR TITLE
Fix reference and typo errors

### PR DESCRIPTION
**Pull request by gmshashank**
Fixed DGL Reference errors for NNconv and MaxPooling in uvnet_encoders.py
Fixed import error for unittest in test_dataloader.py and test_dataloaders_equivalent.py
Fixed typo errors in quickstart.py and build_dataset_file.py

### CODE REVIEW

**Comment by JoeLambourne** [comment]
Hi @gmshashank,

Thank you for your contribution and sorry for the slow reply.  Looks like the missing  DGL reference might be a copy and paste error on my part when I added support for the UV-Net input features.  Are you using the graph encoder?   I think it would be better if I removed it.   If you want to work with UV-Net the the source code is also available [here](https://github.com/AutodeskAILab/UV-Net)

**Comment by gmshashank** [comment]
Hi @JoeLambourne,
Thank you for replying to my Pull Request.
I have created a separate Pull Request for fixing some typos (sys.exit(1), unittest) which were also a part of this PR. #8 

**Are you using the graph encoder? I think it would be better if I removed it.** -->I had updated the DGL reference as NNCOnv was used in class _NodeConv and MaxPooling in class UVNetGraphEncoder in the   models/uvnet_encoders.py.
I had taken the reference of UV-Net source code.

**Comment by JoeLambourne** [comment]
Hi @gmshashank,

I suggest that I remove the unused UV-Net code rather than adding a new dependency on DGL.  I've opened  #9 to do this.   Would you be able to take a quick look and let me know if the changes I'm suggesting would address the issue you flagged here?

Were you using some kind of linter to find these bugs?  Probably I should be doing some similar checking.

**Comment by gmshashank** [comment]
Hi @JoeLambourne,

*Would you be able to take a quick look and let me know if the changes I'm suggesting would address the issue you flagged here?* --> Yes, the changes in this PR would resolve the NNConv and MaxPooling reference error.

*Were you using some kind of linter to find these bugs?* --> I found these bugs using Flake8. 

I use VS Code + Black + Mypy + Flake8 for project development.

I am closing this PR #7 as some changes were resolved with PR #8 and the rest would be resolved with PR #9 
Regards.

**Comment by gmshashank** [comment]
@JoeLambourne,
Apologies, I reopened this pull request by mistake.
Please close this pull request when you merge #9 
Thank you.

**Comment by JoeLambourne** [comment]
Thank you @gmshashank .    Great contributions.   I merged #9  and I will close this.

**Pull request closed without merging**
